[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"

  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0" 