services:
  - type: web
    name: bnsound
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /manifest.json
        name: Cache-Control
        value: public, max-age=3600
      - path: /service-worker.js
        name: Cache-Control
        value: public, max-age=0
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: BUILD_PATH
        value: ./build 